services:
  bacon-batch-publishers-urls:
    image: abesesr/bacon:${BACON_BATCH_PUBLISHERS_URLS_VERSION}
    container_name: bacon-batch-publishers-urls
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    volumes:
      - ${BACON_BATCH_PUBLISHERS_URLS_PATH_KBARTS}:/scripts/local/
    environment:
      MAIL_ADMIN: ${BACON_BATCH_PUBLISHERS_URLS_MAIL_ADMIN}
      MAIL_WS_URL: ${BACON_BATCH_PUBLISHERS_URLS_MAIL_WS_URL}
      BACON_BATCH_PUBLISHERS_AT_STARTUP: ${BACON_BATCH_PUBLISHERS_AT_STARTUP}
      BACON_BATCH_PUBLISHERS_DEPLOY_CRON: ${BACON_BATCH_PUBLISHERS_DEPLOY_CRON}
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=bacon-batch-publishers-urls"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"
      # pour que les mises à jour de cette image soient auto-déployées par watchtower
      - "com.centurylinklabs.watchtower.scope=bacon-batch-publishers-urls-watchtower-scope"

  #  #######################################
  #  # periscope-watchtower
  #  # Conteneur chargé de mettre à jour automatiquement toutes les N secondes
  #  # les images docker des conteneurs surveillés (via le système de label/scope de watchtower)
  #  # plus d'info : https://containrrr.dev/watchtower
  #  # cf README.md pour explications : https://github.com/abes-esr/periscope-docker#d%C3%A9ploiement-continu
  bacon-batch-publishers-urls-watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: bacon-batch-publishers-urls-watchtower
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_DEBUG: "false"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
      WATCHTOWER_RUN_ONCE: ${BACON_BATCH_PUBLISHERS_URLS_WATCHTOWER_RUN_ONCE}
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${BACON_BATCH_PUBLISHERS_URLS_WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: ${BACON_BATCH_PUBLISHERS_URLS_WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER}
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#notif-bacon"
      WATCHTOWER_SCOPE: "bacon-batch-publishers-urls-watchtower-scope"
    labels:
      - "com.centurylinklabs.watchtower.scope=bacon-batch-publishers-urls-watchtower-scope"
